# Generated by Django 4.1.9 on 2023-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("icon", models.ImageField(default="icons/default_icon.png", upload_to="icons/")),
            ],
        ),
    ]
